const { reply } = require('./_helper');
module.exports = async (sock, chatId, message, args) => {
    const text = args.join(' ').trim();
    if (!text) return reply(sock, chatId, '❌ Usage: .texttopdf <text>', message);
    // Create simple HTML-based PDF content
    const html = `<!DOCTYPE html><html><body style="font-family:Arial;padding:20px;"><h1>TunzyMD</h1><p>${text.replace(/\n/g,'<br>')}</p><small>Generated by TunzyMD | TunzyMD©</small></body></html>`;
    await sock.sendMessage(chatId, {
        document: Buffer.from(html),
        fileName: 'document.html',
        mimetype: 'text/html',
        caption: `📄 *Text Document*\n\n_Open in browser for PDF printing_\n\n_spider©_`
    }, { quoted: message });
};
